version: "3"
services:
  database:
    image: "postgres:10.14-alpine"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:
